### ISSUE TITLE
BUG/ISSUE: ASCII Special Character Logo Turn Garbage

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#103]
![image](https://user-images.githubusercontent.com/7589432/228306214-3e89319b-394f-41ae-b261-b2a0a2f72b43.png)

Note: May need to replace the logo with something that doesn't require UTF-8 to render or sth
Also, color issue can be fixed as long as users are running Magus Stock on Windows Powershell (Will be including this point and steps in Userguide)

**Comment by ArtemiszenN** [comment]
possible:
https://patorjk.com/software/taag/#p=display&h=3&v=3&f=Doh&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Slant%20Relief&t=MAGUSSTOCK (i like this q abit)
https://patorjk.com/software/taag/#p=display&f=3-D&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=5%20Line%20Oblique&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Alligator&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Big%20Chief&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Block&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Catwalk&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Georgia11&t=MAGUSSTOCK
https://patorjk.com/software/taag/#p=display&f=Reverse&t=MAGUSSTOCK (woah it's inverted)

**Comment by firwer** [comment]
Can can ill look into these, thanks!
