### ISSUE TITLE
BUG: Dashboard Crash due to AlertList

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#125]
![image](https://user-images.githubusercontent.com/7589432/229124987-7fa84b86-b469-49aa-bbbe-01668d10e7c8.png)
![image](https://user-images.githubusercontent.com/7589432/229125730-735e9b04-cf49-4982-82cc-66a6565d6c1b.png)

To Reproduce:

Put these information into the files:
AlertData.csv:
```1234,2,min```

InventoryData.csv
```0,testItem,123456789012,10,10.0,Uncategorized,2023-03-31T20:10:23.128056100
1,testItem2,123456789013,10,10.0,Uncategorized,2023-03-31T20:10:23.128056100
2,testItem,123456789012,10,10.0,Uncategorized,2023-03-31T20:10:23.128056100
3,testItem2,123456789013,10,10.0,Uncategorized,2023-03-31T20:10:23.128056100
```

Run the app and execute `db`, the app will crash. I have narrowed down the issue to the line shown in the image. I suspect it is due to the item not existing in the alertdata

Suggest may need to improve corruption resistant of the code

**Comment by ArtemiszenN** [comment]
Yeah we will have to harden both files. I can do that after finishing up my CS2102 project. We kinda got lucky the testers didn't test the files.
