### ISSUE TITLE
[PE-D][Tester E] Violations of project constraints: Requires additional application.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W12-3/tp#126]
There appears to be a bug with the ASCII display which differs from what should be seen according to the User Guide. Understanding that the User Guide did suggest to download the Terminal App as opposed to using CMD, I believe this project is constrained such that users should not require another application.

![image.png](https://raw.githubusercontent.com/yixuann02/ped/main/files/053f9dfe-aed3-4df0-a426-774b8688328f.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: yixuann02/ped#1

**Comment by firwer** [comment]
Removed the need to use ANSI-COLOR and terminal. Issue resolved
