### ISSUE TITLE
[PE-D][Tester E] Program crashes after user inputs a wrong format, followed by a correct format using the edit function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W12-3/tp#135]
![image.png](https://raw.githubusercontent.com/yixuann02/ped/main/files/bb7e80af-d68c-47db-9133-a2574f8d7d5e.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: yixuann02/ped#3

**Comment by ArtemiszenN** [comment]
Same issue as https://github.com/AY2223S2-CS2113-W12-3/tp/issues/178, closed due to duplicate
