### ISSUE TITLE
[PE-D][Tester E] Duplicates in search results for search functionality.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W12-3/tp#143]
Even though there is only one item in the list, the search functionality returns a duplicate of the same item and prints in the list.

![image.png](https://raw.githubusercontent.com/yixuann02/ped/main/files/894d0b1b-67ed-4d38-8ae5-c9b9392ed1aa.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yixuann02/ped#6

**Comment by ArtemiszenN** [comment]
Fixed a few days ago but forgot to close. Resolved.
