### ISSUE TITLE
[PE-D][Tester A] unclear filter command usage

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W12-3/tp#153]
**The orange part**  - There is no explanation how to use p/[gt/get/lt/let], and what are the differences between 'gt' , 'get', 'lt', and 'let'. The output are different, so took me while to understand how each of this work.

![image.png](https://raw.githubusercontent.com/JuneNita/ped/main/files/2ba20fe5-9800-4ab0-acf2-2caab440b063.png)

![image.png](https://raw.githubusercontent.com/JuneNita/ped/main/files/2354d1fd-77a6-4a8b-a42e-97077c19545f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: JuneNita/ped#3

**Comment by ArtemiszenN** [comment]
![image](https://user-images.githubusercontent.com/24601679/229261961-5c26c35b-16cc-477c-b812-a66e621b76ff.png)

First example appears to be a rare bug? Not sure how it could have happened tbh.

**Comment by ArtemiszenN** [comment]
Fixed in UG
