### ISSUE TITLE
[PE-D][Tester D] Valid range of qty in sell method

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W12-3/tp#160]
qty, which cannot be decimal, should be stated in the 'sell' method

![image.png](https://raw.githubusercontent.com/kdh3799/ped/main/files/cc0ed801-2814-4d59-944c-a2c50cfbbbd5.png)

![image.png](https://raw.githubusercontent.com/kdh3799/ped/main/files/fe64606a-bf2d-4bca-b1e1-70f2b319bdc5.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: kdh3799/ped#7

**Comment by ngkaiwen123** [comment]
Added string to warn user that decimal quantity inputs are not allowed
![image](https://user-images.githubusercontent.com/88386677/229339562-f3d61fa3-f0c8-4faa-aca3-83e3da7b10c3.png)
