### ISSUE TITLE
[PE-D][Tester B] History Command Displaying does not match UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W12-3/tp#161]
![image.png](https://raw.githubusercontent.com/SpeciLiam/ped/main/files/f4f7c423-d3f5-44fa-947a-d3fc6471f364.png)

The histroy command displayed a bunch of lines with no description.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: SpeciLiam/ped#7

**Comment by ArtemiszenN** [comment]
Likely related to storage error. Also possible user used the edit command but did not edit the item.

**Comment by ArtemiszenN** [comment]
Added fallback code for clarification. Closed.
