### ISSUE TITLE
[PE-D][Tester A] warning typo

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W12-3/tp#163]
When user enter invalid sell command, the error warn the user about restocking.

![image.png](https://raw.githubusercontent.com/JuneNita/ped/main/files/9dcef434-51f7-4fa9-a86a-d61ab90e356a.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: JuneNita/ped#5

**Comment by ngkaiwen123** [comment]
Fixed
![Screenshot (416)](https://user-images.githubusercontent.com/88386677/229339190-e07fe814-0c0f-4381-a35e-392a85016dba.png)
