### ISSUE TITLE
[PE-D][Tester E] Unclear format for edit functionality.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W12-3/tp#175]
Following the format as suggested in the help table, the edit functionality seems to take in the curly brackets as part of the Name inputs.

![image.png](https://raw.githubusercontent.com/yixuann02/ped/main/files/ca58c985-a354-4a76-90c2-cdfb870a6c61.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: yixuann02/ped#13

**Comment by ngkaiwen123** [comment]
Will change user guide. Curly brackets which were meant to represent a selection of different inputs is misinterpreted as a valid format.

**Comment by firwer** [comment]
User Guide changed in the latest PR. Resolved
![image](https://user-images.githubusercontent.com/7589432/229292637-218bf7d9-7cce-425d-b9fe-6a517f27f5b5.png)
