### ISSUE TITLE
[PE-D][Tester B] Crashed when editing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W12-3/tp#178]
![image.png](https://raw.githubusercontent.com/SpeciLiam/ped/main/files/c95d94bd-0ada-4e9c-9517-03667a1c063e.png)

When trying to edit upc 3 it crashed after following guidelines in UG

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SpeciLiam/ped#9

**Comment by ArtemiszenN** [comment]
Bug happens because edit function can still edit item even if part of the input is invalid.

Get item by reference -> start editing the item (changes item in inventory too) -> gets error, aborts -> changes not handled by setEditInfo() -> crash

**Comment by firwer** [comment]
Upgraded issue due to possibility of crash

**Comment by firwer** [comment]
Linked to #148

**Comment by ngkaiwen123** [comment]
> Bug happens because edit function can still edit item even if part of the input is invalid.
> 
> Get item by reference -> start editing the item (changes item in inventory too) -> gets error, aborts -> changes not handled by setEditInfo() -> crash

Resolved this issue as shown below. Attributes revert to old value even if small portion of command is invalid. Bug shown above no longer causes a crash.
![Screenshot (411)](https://user-images.githubusercontent.com/88386677/229274397-9cfaa632-904e-4d43-aae7-97067616a62d.png)

Below shows that attributes remains unchanged even if subsequent inputs or inputs before invalid input is valid. In the example shown below, qty input is invalid, but name and price is valid. Correct error message returned and list is not updated.
![image](https://user-images.githubusercontent.com/88386677/229274537-d989f018-48fd-4c88-b71b-f2282055dc00.png)
![image](https://user-images.githubusercontent.com/88386677/229274558-12d52f6c-107a-49f2-a0c2-a5052daec883.png)

**Comment by ArtemiszenN** [comment]
Has the change been pushed to master? Feel free to close if so.

**Comment by ngkaiwen123** [comment]
> Has the change been pushed to master? Feel free to close if so.

Yep, pushed to master, will close it now.
