### ISSUE TITLE
[TA Code Review] for Artemis

### ISSUE THREAD

**Issue by kohnh** [AY2223S2-CS2113-W12-3/tp#188]
@ArtemiszenN 
Overall, good job on following the coding standards and conventions. I see good use of constructor overloading in your code and also using knowledge from CS2040C. Good job creating JUnitTests.

- [x] In the printHistory method there seems to be deep nesting maybe you can refactor the code
- [x] It seems that ` System.out.println(LINE);`  and the different colors that you used is repeated quite a lot in your code. You have somewhat abstract this calls into a new method but did not use it.
- [x] In `filterParser.java` there seems to be case statement without `//fallthrough` lines 25 - 27
- [x] Javadocs should be more informative and not a grammatically correct way of reading the method name
- [x] Try not to use magic numbers and string literals. Maybe try making them static final variables wherever possible as you have done for the majority.
- [x] In the `TrieNode.java` line 7 maybe can consider the plural form since it is a collection of `TrieNodes`
- [ ] While I have listed some specific issues in certain classes, please make the appropriate changes if you see them in any other areas

**Comment by ArtemiszenN** [comment]
But children is the plural form, the singular form is child XD

**Comment by kohnh** [comment]
Oops my bad you can ignore that
