### ISSUE TITLE
[TA Code Review] for Wei Pin

### ISSUE THREAD

**Issue by kohnh** [AY2223S2-CS2113-W12-3/tp#191]
@firwer
Overall, good job on following the coding standards and conventions. your code is quite neat especially the JavaDocs alignment.

- [x] In `Storage.java` `readCSV()` seems to be quite long and is quite nested. Maybe you can try abstracting parts of the code. 
- [x] Additionally, in line 137 the exception level of abstraction seems to be not consistent with your other parts of the code where you catch exceptions.
- [x] There also seems to be some arrowhead code, maybe you can try refactoring.
- [x] It seems that ` System.out.println(LINE);`  and the different colors that you used is repeated quite a lot in your code. You have somewhat abstract this calls into a new method but did not use it.
- [ ] In ` FilterCommand.java` there seems to be case statement without `//fallthrough` lines 143 – 146
- [x] In `Inventory.java` the methods ` getItemWithMostQuantity()` and ` getItemWithLeastQuantity()` seems to be pretty similar maybe you can try combining both into one to reduce duplicate code.
- [x] While I have listed some specific issues in certain classes, please make the appropriate changes if you see them in any other areas

**Comment by firwer** [comment]
@kohnh for FilterCommand.java can you point out where is it again? I can't seem to find it

**Comment by kohnh** [comment]
`public ArrayList<Item> getFilteredItems() {
        ArrayList<Item> filteredItems = new ArrayList<>();
        switch (filterType) {
        case "f/category":
            filteredItems = filterCategory(filterValue);
            break;
        case "p/lt":
        case "p/gt":
        case "p/let":
        case "p/get":
            filteredItems = filterPrice(filterPrice, filterType);
            break;
        default:
            break;
        }
        return filteredItems;
    }`
In this part of the code your case statements ie `p/lt` has no `//fallthrough` which might cause readers to not know if there is supposed to be code there
