### ISSUE TITLE
BUG: Category name is displayed changed without been updated by the user.

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#225]
Step to reproduce a bug –
1.	Open CMD prompt and run the command like – Run the file with the command “java -jar magusstock.jar” to open the file.
2.	Now run “List” command to view the inventory list.
3.	Now run “edit” command and try editing the category name.
4.	Here category name starts to display under before update section.
Actual result – When the user tries to edit the category name from uncategorized to some random category, here updated category name starts to display in the before update section.
Expected result – Updated category name should not be displayed in the before update section, when the user tries to edit the category of the added item.
Severity – High
Video link – https://drive.google.com/file/d/1QLyNq9sIScCbxMfoYJiszA1-aB-GR389/view?usp=share_link 
Screenshot – 
 
![image](https://user-images.githubusercontent.com/7589432/230435279-88e3cefe-808a-485a-8bf2-5fe686ac6ea3.png)

**Comment by ngkaiwen123** [comment]
Resolved. Issue due to dual updating of category which results in tracking of previous category being removed.
![image](https://user-images.githubusercontent.com/88386677/230481554-9b6733a8-a717-4df2-a0da-61c25be1825b.png)
