### ISSUE TITLE
BUG: Updated category name with first letter is not displaying in uppercase

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#226]
Preconditions: - 1. Ensure that you have Java 11 or above installed.
                           2. Create some random inventory without any category.
Step to reproduce a bug –
1.	Open CMD prompt and run the command like – Run the file with the command “java -jar magusstock.jar” to open the file.
2.	Now run “List” command to view the inventory list.
3.	Now run “edit” command and try editing the category name.
4.	Now enter the new category name with first letter in uppercase, here after successful updating the category name first letter is not displayed in uppercase.
Actual result – When the user tries to edit the category name from uncategorized to some random category, here updated category name starts to display in the before update section.
Expected result – Updated category name should not be displayed in the before update section, when the user tries to edit the category of the added item.
Severity – Medium
Video link – https://drive.google.com/file/d/1IWU2gW9RNiE_agaj53iHo5_--W6ZQe_w/view?usp=share_link 
Screenshot – 
![image](https://user-images.githubusercontent.com/7589432/230435565-5a01b325-1e81-472c-9fe8-1a45b70e845d.png)

**Comment by ngkaiwen123** [comment]
Resolved. Now supports capital letters.
![image](https://user-images.githubusercontent.com/88386677/230484632-e2e6fc9c-15bb-453f-8fa9-f061d41830ec.png)
