### ISSUE TITLE
BUG: Incorrect error message is displayed when trying to remove the item using existing UPC from the inventory list.

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#227]
Preconditions: - 1. Ensure that you have Java 11 or above installed.
                           2. Create some random inventory must be present.
Step to reproduce a bug –
1.	Open CMD prompt and run the command like – Run the file with the command “java -jar magusstock.jar” to open the file.
2.	Now run “List” command to view the inventory list.
3.	Now run “remove” command and try removing the category using UPC option.
4.	Here error message is displayed like “Command failed! Reason: Item not found in database. Please add item first!”.
Actual result – When the user tries to remove an inventory using remove UPC option, here error message is displayed like “Command failed! Reason: Item not found in database. Please add item first!”.
Expected result – Error message should not be displayed when the user tries to remove an inventory using UPC option.
Severity – Medium
Video link – https://drive.google.com/file/d/1RCv53eNDG6PO9apPr_f5x6Br23KJqLeS/view?usp=share_link 
Screenshot – 
![image](https://user-images.githubusercontent.com/7589432/230435740-aacd6982-bfcc-4225-a029-54c3b0159cd3.png)

**Comment by ArtemiszenN** [comment]
![image](https://user-images.githubusercontent.com/24601679/230505900-68926313-1495-4232-91e0-acb18c051495.png)

![image](https://user-images.githubusercontent.com/24601679/230505997-d6a5157a-60e5-4099-b602-82b41f136729.png)

Can't replicate so far.

**Comment by firwer** [comment]
![image](https://user-images.githubusercontent.com/7589432/230702217-b0a8dfcf-160d-46d1-bf30-303deb46955b.png)

Bug is valid, seems to be quite erratic, need to try a few time for it to be seen

**Comment by ArtemiszenN** [comment]
Could it be because add or remove or edit doesn't remove trailing spaces from upc? Don't have access to the code for today

**Comment by firwer** [comment]
Resolved, no issue at all.
