### ISSUE TITLE
Category declaration bug using ADD function due to capitalization

### ISSUE THREAD

**Issue by ngkaiwen123** [AY2223S2-CS2113-W12-3/tp#241]
Category does not recognise capital letters and treats it as a completely new category, when in fact it is the same.

As shown in the first picture, the category "Fruits and Vegetables" has been declared previously, but a new addition of the same category with capital letters will cause program to recognise it as a new category and claim that category does not exist.
![image](https://user-images.githubusercontent.com/88386677/230708210-3515b489-e33b-431b-9260-ff824041515a.png)

However, when a new item is added with no capitalization, the category is recognised. No message saying "category does not exist" appeared.
![image](https://user-images.githubusercontent.com/88386677/230708248-88d5eb4a-2021-4690-a491-2048cccc11ed.png)

**Comment by ngkaiwen123** [comment]
On the other hand, edit command supports capitalization and will create a new category consisting of capital letters.
![image](https://user-images.githubusercontent.com/88386677/230708657-d02529f0-ea76-415f-86b3-1f05f76695b3.png)
How do we standardize this? Should cat list list out everything in small letters only? Or should capital and small letters be considered different?

**Comment by firwer** [comment]
Latest PR added tolower() for add command input for category
