### ISSUE TITLE
DG: Manual Testing Section

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#251]

**Comment by ngkaiwen123** [comment]
Manual Testing section is up. Left history and alert section of manual testing is undone.

**Comment by ngkaiwen123** [comment]
o wait so you added stuff for the history and alert portion already?

**Comment by Ng-YZ** [comment]
Yea, but it's all good, I resolved the conflict in your PR already :) just help look through again, I might have overlooked some bits.

**Comment by ngkaiwen123** [comment]
Ah ok, looks good to me!
