### ISSUE TITLE
Bug: Possible to add item with price/quantity = 0 but InventoryData file becomes corrupted

### ISSUE THREAD

**Issue by ysl-28** [AY2223S2-CS2113-W12-3/tp#257]
It's possible to add an item with price = 0 or quantity = 0 successfully through the program, but on startup the inventory data file's status will be corrupted. Probably because `checkFileValidSession` will return corrupt file status when `qty <= 0`/`price <= 0` .

![quantity_0_corrupt](https://user-images.githubusercontent.com/88529907/230792040-2219c89d-14d2-4550-85ed-5b6da9fb419f.PNG)

**Comment by ArtemiszenN** [comment]
yes `checkFileValid` will return corrupt file status in that case

**Comment by ArtemiszenN** [comment]
Resolved
