### ISSUE TITLE
BUG/ISSUE: Edit Command Unhandled Error & Incorrect Output

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#43]
Incomplete/wrong but not reflecting correct output (still show successfully)

![image](https://user-images.githubusercontent.com/7589432/226156189-c41d5138-39b1-4746-913e-cbc37e5ac99e.png)
![image](https://user-images.githubusercontent.com/7589432/226156194-63adfeac-d903-4412-8ab8-9731ded8560a.png)

On restart to a new session, typing “edit” alone will give us this error: (unhandled)
![image](https://user-images.githubusercontent.com/7589432/226156200-a36da55a-c999-432f-8c9b-5b46991f7d8d.png)

**Comment by ngkaiwen123** [comment]
Bug is fixed. Wrong formatting will no longer result in update string being printed.
![image](https://user-images.githubusercontent.com/88386677/226719641-40209ccd-928e-44d3-b41d-12d27814357b.png)

Typing of 'edit' command with no user inputs following it will no longer result in a crash, but a printing of wrong format instead.
![image](https://user-images.githubusercontent.com/88386677/226719936-a2e60424-cf9b-407c-8473-107df9ffa55b.png)
