### ISSUE TITLE
BUG/ISSUE: Search by keyword not working

### ISSUE THREAD

**Issue by firwer** [AY2223S2-CS2113-W12-3/tp#44]
When user input search for certain keyword term, search result doesn't seem to work as expected. (In this case, laptop works, la also works but sleeves, s, sle doesn't)

![image](https://user-images.githubusercontent.com/7589432/226156941-29c6e5aa-28ed-4452-828a-ea0476847b1a.png)

**Comment by ArtemiszenN** [comment]
Not a bug; missing functionality/issue. Fix is to add individual words to the itemNameHash and trie for a product instead of the whole product name, but adds complexity, hence low priority issue.
