### ISSUE TITLE
Weird sounding error message when removing by index goes wrong and there is only one item

### ISSUE THREAD

**Issue by ArtemiszenN** [AY2223S2-CS2113-W12-3/tp#75]
![image](https://user-images.githubusercontent.com/24601679/227775020-c9b51ea2-4b46-4b75-ac8f-fcfaad389ce1.png)

**Comment by firwer** [comment]
@ArtemiszenN is this one fixed alr?

**Comment by ArtemiszenN** [comment]
not yet

**Comment by firwer** [comment]
fixed
