### ISSUE TITLE
Can't edit items to have names of more than one word

### ISSUE THREAD

**Issue by ArtemiszenN** [AY2223S2-CS2113-W12-3/tp#76]
![image](https://user-images.githubusercontent.com/24601679/227775077-10aa7d8d-3bba-4ad5-b9c2-bca915ecb1b4.png)

**Comment by ngkaiwen123** [comment]
![image](https://user-images.githubusercontent.com/88386677/228301008-e163499f-222f-407e-848e-903d264eef51.png)
Resolved edit issue
